[package]
name = "custom-headers-and-txs-node"
version = "0.0.0"
publish = false
edition.workspace = true
license.workspace = true

[dependencies]
reth.workspace = true
reth-chainspec.workspace = true
reth-node-core.workspace = true
reth-node-ethereum = { workspace = true, features = ["test-utils"] }
futures-util.workspace = true

alloy-consensus = { workspace = true, features = ["serde"] }
alloy-serde = { workspace = true, optional = true }
reth-basic-payload-builder.workspace = true
reth-evm.workspace = true
reth-network.workspace = true
reth-node-api.workspace = true
reth-node-builder.workspace = true
reth-provider.workspace = true
reth-transaction-pool.workspace = true
reth-trie-db.workspace = true
reth-primitives.workspace = true
reth-primitives-traits.workspace = true
reth-codecs.workspace = true
alloy-rlp.workspace = true

eyre.workspace = true
tokio.workspace = true
serde_json.workspace = true
serde = { workspace = true, features = ["derive"], optional = true }
bincode.workspace = true

alloy-genesis.workspace = true
alloy-primitives.workspace = true

[features]
default = ["serde", "alloy-serde"]
